merge upstream

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -219,6 +219,7 @@ jobs:
 
     env:
       SWIGLANG: ${{ matrix.SWIGLANG }}
+      compiler: ${{ matrix.compiler }}
       PY2: ${{ matrix.PY2 }}
       VER: ${{ matrix.VER }}
       ENGINE: ${{ matrix.ENGINE }}
@@ -227,13 +228,26 @@ jobs:
       CSTD: ${{ matrix.CSTD }}
       CPPSTD: ${{ matrix.CPPSTD }}
       CPPFLAGS: ${{ matrix.CPPFLAGS }}
-      COMPILER: ${{ matrix.compiler || 'gcc' }}
+      PY_ABI_VER: ${{ matrix.PY_ABI_VER }}
       ASAN: ${{ matrix.ASAN }}
+      RELOCATABLE: ${{ matrix.RELOCATABLE }}
 
     steps:
+    - name: Machine Info
+      run: |
+          echo "nproc..."
+          nproc --all
+          echo "uname..."
+          uname --all
+          echo "meminfo..."
+          cat /proc/meminfo
+          echo "lsb-release..."
+          cat /etc/lsb-release
+
     - name: Checkout
-      uses: actions/checkout@v4
+      uses: actions/checkout@v6
       with:
+        show-progress: false
         submodules: recursive
 
     - name: Install CCache
@@ -248,96 +262,43 @@ jobs:
     - name: Install Dependencies
       run: |
           set -x
-          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
-          echo PATH="$PATH" >> $GITHUB_ENV
-
           source $GITHUB_WORKSPACE/Tools/GHA-linux-install.sh
-          echo WITHLANG="$WITHLANG" >> $GITHUB_ENV
 
-          case $(uname) in
-              Linux)
-                  cpu_count=$(nproc)
-                  ;;
-
-              Darwin)
-                  cpu_count=$(sysctl -n hw.ncpu)
-                  ;;
-
-              *)
-                  cpu_count=1
-                  ;;
-          esac
-
-          if [[ $cpu_count != 1 ]]; then
+          cpu_count=$(nproc)
+          if test $cpu_count -gt 1; then
             echo SWIGJOBS=-j$cpu_count >> $GITHUB_ENV
           fi
-
-          if test '${{ matrix.compiler }}' = 'clang'; then
-            CC="clang"
-            CXX="clang++"
-
-            CFLAGS="$CFLAGS -fPIE"
-            CXXFLAGS="$CXXFLAGS -fPIE"
-          elif test '${{ matrix.compiler }}' = 'emscripten'; then
-            git clone https://github.com/emscripten-core/emsdk.git
-            (
-              cd emsdk
-              git pull
-              sh ./emsdk install latest
-              sh ./emsdk activate latest
-            )
-            source $GITHUB_WORKSPACE/emsdk/emsdk_env.sh
-            echo EMSDK=$EMSDK >> $GITHUB_ENV
-            echo EMCC_LOGGING=0 >> $GITHUB_ENV
-
-            TARGET_CC="emcc"
-            TARGET_CXX="em++"
-            CC="cc"
-            CXX="c++"
-
-          elif test -n "$GCC"; then
-            CC="gcc-$GCC"
-            CXX="g++-$GCC"
-          else
-            CC="gcc"
-            CXX="g++"
-          fi
-
-          [ -z "$TARGET_CC" ] && TARGET_CC="$CC"
-          [ -z "$TARGET_CXX" ] && TARGET_CXX="$CXX"
-
-          export CC CXX TARGET_CC TARGET_CXX
-
-          echo CC="$CC" >> $GITHUB_ENV
-          echo CXX="$CXX" >> $GITHUB_ENV
-          echo TARGET_CC="$TARGET_CC" >> $GITHUB_ENV
-          echo TARGET_CXX="$TARGET_CXX" >> $GITHUB_ENV
-
-          ls -la $(which $CC) $(which $CXX) $(which $TARGET_CC) $(which $TARGET_CXX)
-          $CC --version
-          $CXX --version
-          $TARGET_CC --version
-          $TARGET_CXX --version
 
     - name: Configure
       run: |
           source $GITHUB_WORKSPACE/Tools/CI-linux-environment.sh
           set -x
 
-          if [[ -z "$CSTD" ]]; then
+          if test -z "$CSTD"; then
             case "$CPPSTD" in
-              c++11) export CSTD=c11 ;;
-              c++14) export CSTD=c11 ;;
-              c++17) export CSTD=c17 ;;
-              c++20) export CSTD=c17 ;;
+              c++11) CSTD=c11 ;;
+              c++14) CSTD=c11 ;;
+              c++17) CSTD=c17 ;;
+              c++20) CSTD=c17 ;;
             esac
-            echo CSTD="$CSTD" >> $GITHUB_ENV
+            if test -n "$CSTD"; then echo "CSTD=$CSTD" >> $GITHUB_ENV; fi
           fi
-          if test -z "$CPPSTD"; then CONFIGOPTS+=("--disable-cpp11-testing"); fi
-          if test -n "$CPPSTD"; then CONFIGOPTS+=("CXXFLAGS=-std=$CPPSTD $CXXFLAGS"); fi
-          if test -n "$CSTD"; then CONFIGOPTS+=("CFLAGS=-std=$CSTD $CFLAGS"); fi
+          if test -n "$CPPSTD"; then
+            CONFIGOPTS+=("CXXFLAGS=-std=$CPPSTD $CXXFLAGS")
+            echo "Use C++ standard $CPPSTD"
+          else
+            CONFIGOPTS+=("--disable-cpp11-testing")
+            $CXX -x c++ -dM -E - < /dev/null | grep __cplusplus
+          fi
+          if test -n "$CSTD"; then
+            CONFIGOPTS+=("CFLAGS=-std=$CSTD $CFLAGS")
+            echo "Use C standard $CSTD"
+          else
+            $CC -dM -E - < /dev/null | grep __STDC_VERSION__
+          fi
           if test -n "$SWIGLANG"; then CONFIGOPTS+=(--without-alllang --with-$WITHLANG); fi
           if test "$PY2" = "2"; then CONFIGOPTS+=(--with-python=python2 --without-python3); fi
+          if test -n "$RELOCATABLE"; then CONFIGOPTS+=(--with-swiglibdir=swiglib --enable-relocatable); fi
           echo "${CONFIGOPTS[@]}"
           ./autogen.sh && mkdir -p build/build && cd build/build && ../../configure "${CONFIGOPTS[@]}"
 
@@ -354,30 +315,49 @@ jobs:
           source $GITHUB_WORKSPACE/Tools/CI-linux-environment.sh
           set -x
 
+          if test -n "$RELOCATABLE"; then
+            if ! test "`./swig -swiglib`" = "`pwd`/swiglib"; then
+              exit 1
+            fi
+          fi
+
           if test -z "$SWIGLANG"; then
             make $SWIGJOBS check-ccache
             make $SWIGJOBS check-errors-test-suite
           else
             case "$SWIGLANG" in
-              javascript)
-                case "$ENGINE" in
-                  v8 | jsc)
-                    # Running tests using v8 or jsc involves creating a custom
-                    # interpreter in Tools/javascript, which is currently broken
-                    # for parallel builds (we attempt to update this interpreter
-                    # while running, resulting in "Text file busy" error).
+              ocaml)
+                # `make check-ocaml-test-suite` fails with parallel make with:
+                #
+                # File "swig.ml", line 1:
+                # Error: Could not find the .cmi file for interface swig.mli.
+                #
+                # Apparently we ought to be using `ocamldep` to generate make
+                # dependencies.
+                unset SWIGJOBS
+                ;;
+              scilab)
+                case $VER in
+                  ""|6.*|2023.*|2024.0.*|2024.1.*)
+                    # Some older versions of scilab sporadically fail with:
+                    # terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
+                    # #2942 says that it was probably introduced in 6.x (we've
+                    # seen it with 6.1.0.0, but haven't with 5.x); it also says
+                    # "this issue was fixed in Scilab 2024.1.0" but we are
+                    # still seeing sporadic failures with that version.
                     unset SWIGJOBS
+                    ;;
                 esac
                 ;;
             esac
 
             # Stricter compile flags for examples. Various headers and SWIG generated code prevents full use of -pedantic.
-            cflags=$($GITHUB_WORKSPACE/Tools/testflags.py --language $SWIGLANG --cflags --std=$CSTD --compiler=$CC)
-            cxxflags=$($GITHUB_WORKSPACE/Tools/testflags.py --language $SWIGLANG --cxxflags --std=$CPPSTD --compiler=$CC)
+            cflags="$($GITHUB_WORKSPACE/Tools/testflags.py --language $SWIGLANG --cflags --std=$CSTD --compiler=$CC)"
+            cxxflags="$($GITHUB_WORKSPACE/Tools/testflags.py --language $SWIGLANG --cxxflags --std=$CPPSTD --compiler=$CC)"
             make check-$SWIGLANG-version
             make check-$SWIGLANG-enabled
-            make $SWIGJOBS check-$SWIGLANG-examples CFLAGS="$cflags" CXXFLAGS="$cxxflags"
-            make $SWIGJOBS check-$SWIGLANG-test-suite CC="$TARGET_CC" CXX="$TARGET_CXX" CFLAGS="$cflags" CXXFLAGS="$cxxflags"
+            make $SWIGJOBS check-$SWIGLANG-examples CFLAGS="$cflags" CXXFLAGS="$cxxflags" PY_ABI_VER="$PY_ABI_VER"
+            make $SWIGJOBS check-$SWIGLANG-test-suite CC="$TARGET_CC" CXX="$TARGET_CXX" CFLAGS="$cflags" CXXFLAGS="$cxxflags" PY_ABI_VER="$PY_ABI_VER"
           fi
 
     - name: Install
